In [1]:
import numpy as np

In [3]:
np.array([1,2,3,45,6])

array([ 1,  2,  3, 45,  6])

In [4]:
a=np.array([1,2,3,45,6])

In [25]:
b=np.array([5,67,8,9,422,2.1])

In [6]:
a[0],a[1]

(1, 2)

In [13]:
a[0:]

array([ 1,  2,  3, 45,  6])

In [8]:
a[1:3]

array([2, 3])

In [11]:
a[1:-1]

array([ 2,  3, 45])

In [18]:
a[::2]

array([1, 3, 6])

In [19]:
b

array([  5,  67,   8,   9, 422,   2])

In [21]:
b[0], b[2]

(5, 8)

In [22]:
a

array([ 1,  2,  3, 45,  6])

In [23]:
a.dtype

dtype('int32')

In [26]:
b.dtype

dtype('float64')

In [28]:
np.array([1,2,3,4,5], dtype=np.float)

array([1., 2., 3., 4., 5.])

In [29]:
np.array([1,2,3,4,5], dtype=np.int8)

array([1, 2, 3, 4, 5], dtype=int8)

In [30]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [31]:
A[2]

array([7, 8, 9])

In [32]:
A[1,2]

6

In [36]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [45]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [46]:
A[:2,2:]

array([[3],
       [6]])

In [49]:
A[1] = np.array([10,10,10])

In [50]:
A[2] = 99

In [51]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [52]:
a = np.array([1,2,3,4])

In [53]:
a.sum()

10

In [54]:
a.mean()

2.5

In [55]:
a.std()

1.118033988749895

In [56]:
a.var()

1.25

In [57]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [58]:
A.sum()

45

In [59]:
A.sum(axis=1)

array([ 6, 15, 24])

In [60]:
A.sum(axis=0)

array([12, 15, 18])

broadcasting and vectorized operations

In [61]:
a =np.arange(4)

In [62]:
a

array([0, 1, 2, 3])

In [73]:
a + 10

array([120, 121, 122, 123])

In [74]:
a

array([110, 111, 112, 113])

In [75]:
a += 100

In [76]:
a

array([210, 211, 212, 213])

In [77]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [78]:
a

array([0, 1, 2, 3, 4])

Boolean Arrays

In [81]:
a = np.arange(4)

In [82]:
a

array([0, 1, 2, 3])

In [83]:
a[1], a[3]

(1, 3)

In [86]:
a[[True,False,False,True]]

array([0, 3])

In [87]:
a

array([0, 1, 2, 3])

In [88]:
a>=2

array([False, False,  True,  True])

In [89]:
a = np.arange(5)
print(a <= 3)

[ True  True  True  True False]


Linear Algebra